name: Keep Alive Render Service

on:
  schedule:
    # UTC（協定世界時）で10分おきに実行
    # (cronの書式。詳しくは'crontab guru'とかで調べてみて)
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Render API (and DB)
        run: curl -s "https://chatcradt-api.onrender.com/health-check" > /dev/null